#!/usr/bin/env bash
#
# build-agents-md.sh — assemble a box's global agent instructions (the file
# installed as ~/.agents/AGENTS.md, symlinked to ~/.claude/CLAUDE.md and
# ~/.dsh/AGENTS.md) from the machine repo's blueprint.
#
# Shared by the machine repos (generalizes my-system's users/dev/build-claude-md.sh).
# Each machine repo owns its blueprint — the box-specific, handwritten prose — and
# calls this to build it. Two phases:
#   1. Regenerate the generated sections the blueprint uses. Today that is
#      {{repo-descriptions}}: the repos cloned under /srv/dev/repos on THIS box,
#      written by generate-repo-descriptions.sh into the caller's sections dir.
#   2. Assemble --out from --blueprint, replacing each whole-line {{token}} with
#      sections/<token>.md, looked up in the caller's --sections dir first and then
#      in dev-env's own sections/ (the SHARED sections, e.g. {{shared}}, identical
#      on every box). Whole-line <!-- ... --> blueprint comments are dropped.
# An unresolved {{token}} fails the build, so a half-assembled file is never written.
#
# Usage:
#   build-agents-md.sh --blueprint <file> --sections <dir> --out <file> --cache <dir> [--force]
#     --force   re-fetch every repo description (bypass the description cache)

set -euo pipefail

LIB_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
SHARED_SECTIONS_DIR="$(cd "$LIB_DIR/.." && pwd)/sections"

BLUEPRINT="" SECTIONS_DIR="" OUT_FILE="" CACHE_DIR="" FORCE_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --blueprint) BLUEPRINT="${2:-}"; shift 2 ;;
    --sections)  SECTIONS_DIR="${2:-}"; shift 2 ;;
    --out)       OUT_FILE="${2:-}"; shift 2 ;;
    --cache)     CACHE_DIR="${2:-}"; shift 2 ;;
    -f|--force)  FORCE_ARGS=(--force); shift ;;
    -h|--help)   sed -n '2,23p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
if [ -z "$BLUEPRINT" ] || [ -z "$SECTIONS_DIR" ] || [ -z "$OUT_FILE" ] || [ -z "$CACHE_DIR" ]; then
  echo "error: --blueprint, --sections, --out and --cache are all required (see --help)" >&2
  exit 2
fi
[ -f "$BLUEPRINT" ] || { echo "error: blueprint not found: $BLUEPRINT" >&2; exit 1; }

# Whole-line {{token}} names used by the blueprint (lowercase; {{UPPER}} is reserved
# for dev-env's host-placeholder rendering and is never a section).
tokens="$(sed -n 's/^[[:space:]]*{{\([a-z0-9._-]*\)}}[[:space:]]*$/\1/p' "$BLUEPRINT")"

# --- phase 1: refresh generated sections -------------------------------------
echo "==> Regenerating sections"
if grep -qx 'repo-descriptions' <<<"$tokens"; then
  echo "  - repo-descriptions"
  # Bare (no --force) by default: the generator's cache means a deploy only polls
  # what actually changed.
  "$LIB_DIR/generate-repo-descriptions.sh" "${FORCE_ARGS[@]}" \
    --out "$SECTIONS_DIR/repo-descriptions.md" \
    --cache "$CACHE_DIR/repo-descriptions.json"
fi

# --- phase 2: assemble --------------------------------------------------------
echo "==> Assembling $OUT_FILE from $(basename "$BLUEPRINT")"
mkdir -p "$(dirname "$OUT_FILE")"
tmp="$(mktemp "$OUT_FILE.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- GENERATED by dev-env/lib/build-agents-md.sh from $(basename "$BLUEPRINT") — do NOT edit directly. -->"
  echo "<!-- Edit the blueprint (box-specific prose), the machine repo's sections/, or dev-env/sections/ (shared), then re-run the installer. -->"
  echo
} > "$tmp"

while IFS= read -r line || [ -n "$line" ]; do
  trimmed="${line#"${line%%[![:space:]]*}"}"      # ltrim
  trimmed="${trimmed%"${trimmed##*[![:space:]]}"}" # rtrim
  if [[ "$trimmed" =~ ^\{\{([a-z0-9._-]+)\}\}$ ]]; then
    name="${BASH_REMATCH[1]}"
    if [ -f "$SECTIONS_DIR/$name.md" ]; then
      cat "$SECTIONS_DIR/$name.md"
    elif [ -f "$SHARED_SECTIONS_DIR/$name.md" ]; then
      cat "$SHARED_SECTIONS_DIR/$name.md"
    else
      echo "error: unresolved section {{$name}} (not in $SECTIONS_DIR or $SHARED_SECTIONS_DIR)" >&2
      exit 3
    fi
  elif [[ "$trimmed" =~ ^\<!--.*--\>$ ]]; then
    : # drop the blueprint's own maintainer-guidance comment lines
  else
    printf '%s\n' "$line"
  fi
done < "$BLUEPRINT" >> "$tmp"

chmod 664 "$tmp"   # mktemp defaults to 0600; restore group read
mv "$tmp" "$OUT_FILE"
trap - EXIT
echo "==> Wrote $OUT_FILE"
